# -*- coding: utf-8 -*-
"""
Created on 2021-08-11 20:20:43
---------
@summary:
---------
@author: lanba
"""

from feapder import Item


class EtsyDetailTaskItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i etsy_detail_task.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        # self.state = 0  # 任务状态（0未做，1完成，2正在做，-1失败）
        self.url = None
